Month7/step2
DzhumaMag/react-burger pull request #2
Opened 2022-10-17 04:31 UTC by DzhumaMag

2022-10-17 06:03 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- в репозитории проект должен быть в корне, а не в папке react-burger.

- Исправьте ошибки в консоли браузера:

- Поправить верстку в app-headed. По макету, первая ссылка должна быть выделена:

- Поправить работу с propTypes.

- Вынесите адрес для апи в файл в utils/api.js

### **Сделает код лучше:**

- Используйте прелоадер, для отображения пользователю, что приложение работает над загрузкой данных

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить".**

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/utils/prop-types.js
> +  type: PropTypes.string.isRequired,
**Надо исправить:** 
Лучше написать вот так: 

```js
  type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
```

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/App/App.jsx
> +  const [ingredient, setIngredients] = useState([]);
**Надо исправить:** 

Если данных нет, то следует записывать null а не пустой массив.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/App/App.jsx
> +        <BurgerConstructor data={data} />
**надо исправить:** 

Вы уже получаете данные с сервера, поэтому используйте их.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/App/App.jsx
> +      .then((json) => setIngredients(json.data))
**Надо исправить:** Вместо json лучше использовать название res, от слова result. Так будет более правильно, мы не знаем точно ли там будет Json, или что-то ещё.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
>                if (item.type !== 'bun') {
**Надо исправить:** Эта проверка избыточна, её нужно убрать. Мы ведь уже отсортировали массив ранее, с булками и без.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +    }, { others: [], total: 0, bun: []})
**Можно лучше:** Попробуйте сделать булку объектом, т.е в единственном варианте.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +    const ingredients = data.reduce((res, item) => {
**Можно лучше:** Это лучше обернуть в useMemo, чтобы не было вычислений при ререндере компонента.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +  function closeAllModals() {
**Надо исправить:** Название функции подразумевает, то что будут закрыты все окна, однако закрывается только окно деталей заказа. Лучше так и написать - `closeDetailOrder` или `closeModal`.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +          closeAllModals={closeAllModals}
**Надо исправить:** Тут идёт дублирование обработчиков событий, лучше оставить просто closeAllModal, этого будет достаточно. Также лучше переименовать `closeAllModal` на `onClose`.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +          <OrderDetails closeModal={closeAllModals} />
**Надо исправить:** Стоит убрать пропс closeModal, мы не используем его в компоненте orderDetails.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +        document.querySelector(`#${id}`)?.scrollIntoView({ behavior: 'smooth' });
**Можно лучше:** Лучше использовать useRef, т.к. поиск элемента в DOM дереве дольше, чем запомнить ссылку на него.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +      const closeAllModals = () => {
**надо исправить:** Отметил похожую проблему с названием в burgerConstructor.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/IngredientDetails/IngredientDetails.js
> +    ingredients: ingredientsPropTypes.isRequired,
**Надо исправить:** Описаны не те пропсы, которые используются в компоненте.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerConstructor/BurgerConstructor.js
> +    ingredients: PropTypes.arrayOf(ingredientsPropTypes.isRequired).isRequired,
**Надо исправить:** Описаны не те пропсы, которые используются в компоненте.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +      const [ingredientsModal, setIngredientsModal] = useState(null);
**надо исправить:** Переименуйте в ед.число, потому что вы передаёте туда объект, а не массив.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +        >
**надо исправить:** указал похожую проблему в burgerConstructor.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/IngredientsCard/IngredientsCard.js
>                  className={`${IngredientsCardStyles.price} mt-1 mb-1 text text_type_digits-default`}>
**Надо исправить:** 

ingredients.price - не нужно проверять, там всегда будет значение.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/IngredientsCard/IngredientsCard.js
> +function IngredientsCard({ingredients, count, onIngredientClick}) {
**Надо исправить:** Переименуйте `ingredients` в ед.число. Мы передаем сюда объект а не массив.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/IngredientsCategory/IngredientsCategory.js
> +IngredientsCategory.propTypes = {
**Надо исправить:** Описаны не все пропсы, которые используются в компоненте. Также не забывайте про .isRequired .

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +          ingredients={data}
**Можно лучше:** Лучше сделать фильтрацию в burgerIngredients, и потом уже передавать в нужные секции, нужные компоненты.

```js 
  const buns = useMemo(
    () => ingredients.filter((item) => item.type === "bun"),
    [ingredients]
  );

  const mains = useMemo(
    () => ingredients.filter((item) => item.type === "main"),
    [ingredients]
  );

  const sauces = useMemo(
    () => ingredients.filter((item) => item.type === "sauce"),
    [ingredients]
  );
```

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/BurgerIngredients/BurgerIngredients.js
> +                    value={'bun'}
**Надо исправить:** Здесь и далее во всём проекте. Лучше писать просто вот так: `value="bun"` Тут просто строковое значение, пропсы реакта принимают строки, если нужно передать что-то другое, то нужно использовать фигурные скобки, даже если это число.

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/compponents/Modal/Modal.jsx
> +  children: PropTypes.any,
**Надо исправить:** неправильно описаны propTypes для children. Подробнее, как это сделать правильно: https://ru.react.js.org/docs/typechecking-with-proptypes.html#%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D1%87%D0%B5%D1%80%D0%BD%D0%B5%D0%B3%D0%BE-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0

2022-10-17 06:03 UTC, ArslanMustafin commented on react-burger/src/utils/ingredients.js
> +export const URL = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:** перенесите эту переменную в api.js. Она относится к апи. И еще: вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2022-10-17 06:03 UTC, ArslanDev666 commented on react-burger/src/compponents/App/App.jsx
>  function App() {
**можно лучше:** Используйте прелоадер, для отображения пользователю, что приложение работает над загрузкой данных.

2022-10-20 03:01 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Почти все замечания с 1 ревью, были исправлены.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- Исправить верстку модального окна orderDetails. Нужно убрать синюю обводку у картинки, эта обводка на макете нужна только что бы сделать поясняющее описание к этому блоку;

- Убрать компонент `images.jsx`, и лишние картинки, которые не используются.

- Удалите файл `utils/ingredients.js`, если он не используется.

- Удалите файл `logo.svg`, он остался с инициализации `create-react-app`.

- Поправьте расширения файлов, у вас где-то стоит `.jsx`, а где-то просто `.js`. Если в файле не содержится jsx элементов, то лучше поменять расширение на `.js`. Если в файле есть `jsx`, то ставим расширение `.jsx`.

- В файле index.jsx верните обёртку React.StrictMode, она помогает отслеживать ошибки. https://ru.reactjs.org/docs/strict-mode.html#gatsby-focus-wrapper.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-10-20 03:01 UTC, ArslanMustafin commented on src/images/images.jsx
> +export default InportSVG;
**Надо исправить:** Изображение должно быть сделано по другому, не нужно для этого создавать отдельный компонент. Тут подробнее: https://create-react-app.dev/docs/adding-images-fonts-and-files/.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/Modal/Modal.jsx
> +  }, []);
**Можно лучше:** Лучше передать в зависимости useEffect функцию closeAllModals. Т.к мы не всегда можем быть уверены, что ссылка на функцию будет актуальной.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/Modal/Modal.jsx
> +function Modal({ closeAllModals, children }) {
**Можно лучше:** Название `closeAllModals`, лучше переименовать в `onClose`.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/App/App.jsx
> +  const [ingredient, setIngredients] = useState(data); //eslint-disable-line
**Надо исправить:** Изначально тут должен быть null, а не захардкоженные данные. А также `ingredient`, нужно переименовать в `ingredients`, т.к это множественное число.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/utils/api.js
> +const baseUrl = "https://norma.nomoreparties.space/api"
**Надо исправить:** Имена констант принято записывать в стиле UPPER_CASE

2022-10-20 03:01 UTC, ArslanMustafin commented on src/utils/api.js
> +export const URL = `${baseUrl}/ingredients` ;
**Можно лучше:** В будущем у вас будет много запросов, поэтому лучше напрямую в запросе использовать такую строку, а не создавать дополнительную переменную.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/IngredientsCard/IngredientsCard.js
> +function IngredientsCard({ingredient, count, onIngredientClick}) {
**Можно лучше:** Лучше сменить название `onIngredientClick` на `onClick`. Так будет более понятно, не нужно дополнительно уточнять, по чему вы кликаете, если у вас 1 обработчик событий.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/IngredientsCard/IngredientsCard.js
> +    count: PropTypes.string,
**Надо исправить:** Count - это число, поэтому PropTypes должен быть number.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/IngredientDetails/IngredientDetails.js
> +function IngredientDetails({data}) {
**Можно лучше:** `data` - стоит переименовать в `ingredient`. Так будет более понятно, что тут передаётся.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/BurgerIngredients/BurgerIngredients.js
> +
**Можно лучше:** Лучше назвать `handleTabClick`. Чуть подробнее про `naming`: https://stackoverflow.com/questions/60048249/what-is-the-right-name-of-event-handler-onclick-or-handleclick.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/BurgerConstructor/BurgerConstructor.js
> +  const ingredientsData = data.filter((ingredient) => ingredient.type !== "bun")
**Можно лучше:** Лучше обернуть в `useMemo`, чтобы при ререндере, эти значения не вычислялись заново.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/BurgerConstructor/BurgerConstructor.js
> +  );
**Можно лучше:** Лучше обернуть в `useMemo`, чтобы при ререндере, эти значения не вычислялись заново.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/BurgerConstructor/BurgerConstructor.js
> +  function closeDetailOrder() {
**Можно лучше:** Здесь и во всём проекте. Старайтесь называть функции в одном стиле. В данном случае ниже у вас идёт просто `openModal`, а тут `closeDetailOrder`, и сразу не поймешь, что 2 функция тоже работает с модальным окном (закрывает его).

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/IngredientsCard/IngredientsCard.js
> +                  }}
**Надо исправить:** 

Клик должен происходить если нажали на карточку, поэтому лучше задать `onClick` элементу `section`. 

**Можно лучше:** 

Лучше вынести обработчик событий в отдельную функцию.

2022-10-20 03:01 UTC, ArslanMustafin commented on src/compponents/IngredientsCard/IngredientsCard.js
> +export default IngredientsCard;
**Можно лучше:** Тут можно использовать React.memo, чтобы не было лишних ререндоров этого компонента. 
https://ru.reactjs.org/docs/react-api.html#reactmemo

2022-10-20 03:36 UTC, DzhumaMag commented on src/compponents/IngredientsCard/IngredientsCard.js
> +    count: PropTypes.string,
насколько я поняла count преобразуется в строку когда добавляется _id , поэтому проверка count: PropTypes.number выдает ошибку в консоли. преобразовать в число?

2022-10-20 04:27 UTC, DzhumaMag commented on src/compponents/App/App.jsx
> +  const [ingredient, setIngredients] = useState(data); //eslint-disable-line
вот тут застряла(( теряю отрисовку вовсе если сначала не отрисовываю хардкод. где и что упускаю?

2022-10-20 05:33 UTC, DzhumaMag commented on src/compponents/IngredientsCard/IngredientsCard.js
> +    count: PropTypes.string,
_id содержит буквы

2022-10-20 15:02 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа зачтена. Удачи в дальнейшем обучении🔥.**

- Почти все замечания с прошлого ревью, были исправлены.

### **Всё же рекомендую исправить эти замечания:**

- Компонент `ModalOverlay` тоже должен иметь расширении `.jsx`;

- Удалите файл `utils/ingredients.js`, если он не используется;

- В файле index.jsx верните обёртку React.StrictMode, она помогает отслеживать ошибки. https://ru.reactjs.org/docs/strict-mode.html#gatsby-focus-wrapper.

2022-10-20 15:02 UTC, ArslanMustafin commented on src/compponents/App/App.jsx
> +  const [ingredients, setIngredients] = useState(null); //eslint-disable-line
**Можно лучше:** Сейчас уже можно убрать `//eslint-disable-line`.

2022-10-27 15:50 UTC, merged